<a href="https://colab.research.google.com/github/BingoTop/Pytorch-Study/blob/master/Lab_01_1Tensor_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip3 install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp36-cp36m-linux_x86_64.whl
!pip3 install torchvision

     |████████████████████████████████| 592.3MB 81.9MB/s 
ERROR: torchvision 0.3.0 has requirement torch>=1.1.0, but you'll have torch 0.3.0.post4 which is incompatible.
ERROR: fastai 1.0.55 has requirement torch>=1.0.0, but you'll have torch 0.3.0.post4 which is incompatible.
  Found existing installation: torch 1.1.0
    Uninstalling torch-1.1.0:
      Successfully uninstalled torch-1.1.0
  Using cached https://files.pythonhosted.org/packages/69/60/f685fb2cfb3088736bafbc9bdbb455327bdc8906b606da9c9a81bae1c81e/torch-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
  Found existing installation: torch 0.3.0.post4
    Uninstalling torch-0.3.0.post4:
      Successfully uninstalled torch-0.3.0.post4
ERROR: unknown command "numpy"


In [0]:
import torch
import numpy as np

In [5]:
print(torch.__version__)

1.1.0


In [7]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [8]:
print('Rank of t:', t.ndim)
print("Shape of t:",t.shape)

Rank of t: 1
Shape of t: (7,)


In [10]:
print('t[0] t[1] t[-1] = ',t[0],t[1],t[-1])

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [12]:
print('t[2:5] t[4:-1]',t[2:5],t[4:-1])

t[2:5] t[4:-1] [2. 3. 4.] [4. 5.]


In [13]:
print(t[:2],t[3:])

[0. 1.] [3. 4. 5. 6.]


In [14]:
#2D Array with NumPy
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [16]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)
print(t.dim()) #rank, slice도 가능

tensor([0., 1., 2., 3., 4., 5., 6.])
1


In [18]:
t = torch.torch.FloatTensor([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [21]:
print(t[:,1])
print(t[:,2])
print(t[:,:-1])

tensor([ 2.,  5.,  8., 11.])
tensor([ 3.,  6.,  9., 12.])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [22]:
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([[3],[4]])
print(m1+m2)

tensor([[4., 5.],
        [5., 6.]])


In [27]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print('Shape of Matrix 1:',m1.shape)
print('Shape of Matrix 2:',m2.shape)
print(m1.matmul(m2))

print(m1*m2)
print(m1.mul(m2))



-------------
Mul vs Matmul
-------------
Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [28]:
t = torch.FloatTensor([1,2]) # Long Tensor는 불가능
print(t.mean())

tensor(1.5000)


In [35]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))


tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


In [38]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t.sum())
print(t.max())

tensor(10.)
tensor(4.)


In [37]:
print(t.sum(dim=0))

tensor([4., 6.])


In [44]:
#print(t.max(dim=0)[0])
#print(t.max(dim=0))
print(t.max(dim=0)[1])

tensor([1, 1])
