<a href="https://colab.research.google.com/github/BingoTop/Pytorch-Study/blob/master/Lab_01_2_Tensor_Manipulation2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

In [5]:
t= np.array([[[0,1,2],
            [3,4,5]],
            [[6,7,8],
            [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft)
print(ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


In [7]:
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [9]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape) #view로 원하는 형태로 출력할 수 있다. view 잘 사용해야함.

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [10]:
# Squeuze 쥐어짜다
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)


tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [18]:

print(ft.squeeze(dim=0))

print(ft.squeeze(dim=1))

print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
tensor([0., 1., 2.])
torch.Size([3])


In [22]:
# UnSqueeze dim 꼭 명시
ft = torch.Tensor([0,1,2])
print(ft)
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])


In [36]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)


tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [24]:
# Type Casting
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [25]:
lt.float()

tensor([1., 2., 3., 4.])

In [0]:
bt = torch.ByteTensor([True,False,True,False])

In [27]:
print(bt)

tensor([1, 0, 1, 0], dtype=torch.uint8)


In [28]:
# Concatenate 이어붙이다

x=  torch.FloatTensor([[1,2],[3,4]])
y=  torch.FloatTensor([[5,6],[7,8]])

print(torch.cat([x,y], dim=0)) # 4 by 2

print(torch.cat([x,y], dim=1)) # 2 by 4

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [30]:
# Stacking
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [34]:
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=0))
print(torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)],dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 4., 2., 5., 3., 6.]])


In [35]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [39]:
print(torch.ones_like(x)) # 같은 size에 1이 꽉 참.
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [40]:
# In place Operation

x = torch.FloatTensor([[1,2],[3,4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.)) # 메모리에 저장
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
