<a href="https://colab.research.google.com/github/BingoTop/Pytorch-Study/blob/master/numpystudy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [2]:
# 0으로 채워진 numpy를 만들 수 있다.
zeros = np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
zeros = np.zeros(1)
zeros

array([0.])

In [6]:
ones = np.ones([10]) # 1로 이루어진 size가 10개인 ones
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
ones = np.ones([10,5]) # 1로 이루어진 size가 10 by 5인 ones
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
ones * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [10]:

arr =np.arange(5) # 0부터 5까지 1차원으로 만들어짐
arr

array([0, 1, 2, 3, 4])

In [11]:
arr = np.arange(4,9) # 4부터 8까지 1차원으로 만들어짐
arr

array([4, 5, 6, 7, 8])

In [14]:

arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(9).reshape(3,3)
# 주로 이렇게 쓴다고 함.


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
# Index
nums = [i for i in range(1,6)]
nums

[1, 2, 3, 4, 5]

In [19]:
nums[2:] # index 2부터 5

[3, 4, 5]

In [21]:
nums[:]

[1, 2, 3, 4, 5]

In [22]:
nums[:-1]

[1, 2, 3, 4]

In [28]:
nums[::-1] # 리스트 뒤집기
nums[::1]
nums[::2] # 인덱스 2간격으로
nums[::-1]


[5, 4, 3, 2, 1]

In [30]:
# numpy도 slicing 가능
nums = [1,2,3,4,[1,2,3]]
nums

[1, 2, 3, 4, [1, 2, 3]]

In [33]:
nums[0:4]

[1, 2, 3, 4]

In [38]:
nums[4][0]

1

In [44]:
# slcing
arr = np.arange(0,9).reshape(3,3)
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [45]:
arr[1:,1:]

array([[4, 5],
       [7, 8]])

In [47]:
# Boolean Indexing
data = np.random.randn(3,3)
data

array([[ 2.21028551,  0.50149667, -0.75857819],
       [ 1.57289652,  1.60408109, -1.26280502],
       [ 0.92077621,  0.72648251,  1.8783565 ]])

In [48]:
data <= 0

array([[False, False,  True],
       [False, False,  True],
       [False, False, False]])

In [0]:
data[data <= 0] = 1 # True인 것은 1로 

In [51]:
data

array([[2.21028551, 0.50149667, 1.        ],
       [1.57289652, 1.60408109, 1.        ],
       [0.92077621, 0.72648251, 1.8783565 ]])

In [54]:
# Broadcast
# 행렬끼리 차원 수가 다르거나 shape가 다르거나
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [57]:
arr + np.array([1,2,3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [59]:
# Math Function
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [60]:
arr *5 

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [61]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [62]:
arr + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
arr = np.random.randint(2,size=27).reshape(3,3,3) # 0 < 2인 숫자를 랜덤하게 size 27로 만드는데 shape를 3,3,3로 변경
arr_2 = np.random.randint(2,size=9).reshape(3,3)
arr

array([[[0, 0, 1],
        [0, 1, 1],
        [1, 1, 1]],

       [[1, 0, 1],
        [0, 0, 1],
        [0, 1, 1]],

       [[1, 0, 0],
        [0, 0, 0],
        [1, 1, 1]]])

In [65]:
arr_2

array([[1, 0, 0],
       [1, 0, 1],
       [0, 0, 0]])

In [66]:
arr.shape, arr_2.shape

((3, 3, 3), (3, 3))

In [67]:
arr + arr_2

array([[[1, 0, 1],
        [1, 1, 2],
        [1, 1, 1]],

       [[2, 0, 1],
        [1, 0, 2],
        [0, 1, 1]],

       [[2, 0, 0],
        [1, 0, 1],
        [1, 1, 1]]])

In [68]:
arr * arr_2

array([[[0, 0, 0],
        [0, 0, 1],
        [0, 0, 0]],

       [[1, 0, 0],
        [0, 0, 1],
        [0, 0, 0]],

       [[1, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [69]:
np.sum(arr)

15

In [70]:
np.sum(arr + arr_2)

24

In [71]:
np.max(arr)

1

In [72]:
np.max(arr+arr_2)

2

In [73]:
np.min(arr+arr_2)

0

In [74]:
# 차원의 기준으로 다르게
np.max(arr + arr_2,0) # 기준을 0차원으로 0차원에서 큰 값을 반환해줌

array([[2, 0, 1],
       [1, 1, 2],
       [1, 1, 1]])

In [76]:
np.sum(arr + arr_2, 0) # 인덱스끼리 더함

array([[5, 0, 2],
       [3, 1, 5],
       [2, 3, 3]])

In [78]:
arr,arr_2

(array([[[0, 0, 1],
         [0, 1, 1],
         [1, 1, 1]],
 
        [[1, 0, 1],
         [0, 0, 1],
         [0, 1, 1]],
 
        [[1, 0, 0],
         [0, 0, 0],
         [1, 1, 1]]]), array([[1, 0, 0],
        [1, 0, 1],
        [0, 0, 0]]))

In [79]:
np.sum(arr + arr_2, -1)

array([[2, 4, 3],
       [3, 3, 2],
       [2, 2, 3]])

In [80]:
np.mean(arr) # 평균 값

0.5555555555555556

In [82]:
arr = np.array([1,6,3,7,3,2,9])
arr

array([1, 6, 3, 7, 3, 2, 9])

In [84]:
np.argmax(arr) # 6번 인덱스가 크다 인덱스 반환

6

In [85]:
np.argmin(arr)

0

In [0]:
arr = np.array([3,5,6,6,3,3,1])

In [88]:
np.unique(arr)

array([1, 3, 5, 6])